"""Render the four phase1 TOMLs from a single template.

A previous copy-paste from phase1_hyp_s0.toml to the other three left the
docstring saying "hyperbolic, seed 0" everywhere. More importantly, manually
maintaining four near-identical TOMLs is a recipe for the next silent drift.

This script is the single source of truth for the phase1 TOML shape. It
generates four files from a (shape, seed) matrix; if you need to change a
hyperparameter, edit the template once and re-run.

Usage:
    python scripts/dev/render_phase1_tomls.py
"""
from __future__ import annotations

from pathlib import Path

PHASE1_MATRIX = [
    ("hyperbolic", 0),
    ("hyperbolic", 1),
    ("exponential", 0),
    ("exponential", 1),
]

TEMPLATE = """\
# Phase 1 run: Qwen2.5-3B, {shape} reward, seed {seed}.
# 200 steps x batch_size=64 x G=4 = 64 rollouts/step -> ~16 problems/step.
# Estimated wall: ~80-100 min per run on 2x A100-80GB.
#
# Generated by scripts/dev/render_phase1_tomls.py. Edit the template there.
#
# Watch item: KV pressure. If vLLM OOMs around step 50-100 once the policy
# uses more turns, drop orchestrator.batch_size from 64 -> 32.

max_steps = 200
seq_len = 8192
output_dir = "/cache/runs/phase1_{shape_short}_s{seed}"

# Top-level [ckpt] triggers RLConfig.auto_setup_ckpt (rl.py:476): with this
# present, both trainer.ckpt and orchestrator.ckpt are auto-instantiated, which
# the validate_shared_ckpt_config validator requires (otherwise it errors
# "Trainer checkpoint config is specified, but orchestrator checkpoint config
# is not"). [trainer.ckpt.weights] below sets save_adapter_separately on top.
[ckpt]

[wandb]
project = "interoception"
name = "qwen25-3b-{shape_short}-s{seed}"

[model]
name = "Qwen/Qwen2.5-3B-Instruct"

# --- LoRA wiring. Just [trainer.model.lora] is required; RLConfig.auto_setup_lora
# at rl.py:718 auto-creates orchestrator.model.lora (with name r{{rank}}-a{{alpha}}),
# sets inference.enable_lora=True, and sets inference.max_lora_rank, when this
# block is present. Matches the alphabet_sort production example at b22e768.
# save_adapter_separately ensures the final LoRA adapter is saved cleanly
# (rather than merged into base weights) for downstream inspection.
[trainer.model.lora]
rank = 32
alpha = 32.0
dropout = 0.0
target_modules = ["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"]

[trainer.ckpt.weights]
save_adapter_separately = true

# --- Trainer hyperparameters. prime-rl defaults at this SHA are lr=1e-6 (way
# too low for LoRA RL) and scheduler=constant. The LoRA CI test uses lr=5e-5,
# matched here. kl_tau pinned at the 1e-3 default (be explicit).
[trainer.optim]
type = "adamw"
lr = 5e-5
max_norm = 1.0
betas1 = 0.9
betas2 = 0.999
weight_decay = 0.01

[trainer.loss]
type = "default"  # discriminated union — required so pydantic picks DefaultLossConfig
kl_tau = 1e-3

[trainer.scheduler]
type = "linear"
warmup_steps = 10  # ramp 0 -> lr over first 10 steps
decay_steps = 10   # decay lr -> 0 over last 10 steps (steps 190-200 of 200)
min_lr = 0.0

[orchestrator]
batch_size = 64
rollouts_per_example = 4   # GRPO group size — all G rollouts share target_s per problem
seed = {seed}

[orchestrator.train.sampling]
max_completion_tokens = 256
temperature = 1.0

[[orchestrator.train.env]]
id = "interoception-countdown"
name = "qwen25-3b-{shape_short}-s{seed}-train"
args = {{ problems_jsonl = "/root/data/train.jsonl", target_s_min = 15.0, target_s_max = 120.0, dataset_seed = {seed}, timing_source = "sim", hardware = "A100_80GB", sim_model = "Qwen2.5-3B", max_turns = 16, reward_shape = "{shape}", attempt_bonus = 0.05, max_time_multiplier = 5.0 }}

[orchestrator.eval]
interval = 20

[orchestrator.eval.sampling]
max_completion_tokens = 256
temperature = 0.0   # deterministic eval — the deploy-honest setting

# Four eval cells at T=15, 30, 60, 120 so we can see pacing-as-a-function-of-T
# at the extremes of the training distribution (whole headline claim of the experiment).
# Real timing here — eval is deploy-honest.
# num_examples=100 cuts binomial sampling-noise CI half-width by ~sqrt(100/30) on the eval correctness curve.
[[orchestrator.eval.env]]
id = "interoception-countdown"
name = "eval-t15"
num_examples = 100
rollouts_per_example = 1
args = {{ problems_jsonl = "/root/data/eval.jsonl", target_s_min = 15.0, target_s_max = 15.0, max_turns = 16, reward_shape = "{shape}", attempt_bonus = 0.05, max_time_multiplier = 5.0 }}

[[orchestrator.eval.env]]
id = "interoception-countdown"
name = "eval-t30"
num_examples = 100
rollouts_per_example = 1
args = {{ problems_jsonl = "/root/data/eval.jsonl", target_s_min = 30.0, target_s_max = 30.0, max_turns = 16, reward_shape = "{shape}", attempt_bonus = 0.05, max_time_multiplier = 5.0 }}

[[orchestrator.eval.env]]
id = "interoception-countdown"
name = "eval-t60"
num_examples = 100
rollouts_per_example = 1
args = {{ problems_jsonl = "/root/data/eval.jsonl", target_s_min = 60.0, target_s_max = 60.0, max_turns = 16, reward_shape = "{shape}", attempt_bonus = 0.05, max_time_multiplier = 5.0 }}

[[orchestrator.eval.env]]
id = "interoception-countdown"
name = "eval-t120"
num_examples = 100
rollouts_per_example = 1
args = {{ problems_jsonl = "/root/data/eval.jsonl", target_s_min = 120.0, target_s_max = 120.0, max_turns = 16, reward_shape = "{shape}", attempt_bonus = 0.05, max_time_multiplier = 5.0 }}

[inference]
# enable_lora is auto-set to true by auto_setup_lora when [trainer.model.lora] is present.
enable_fp32_lm_head = true
"""


SHAPE_SHORT = {"hyperbolic": "hyp", "exponential": "exp"}


def main() -> None:
    out_dir = Path(__file__).resolve().parents[2] / "configs" / "rl"
    out_dir.mkdir(parents=True, exist_ok=True)
    for shape, seed in PHASE1_MATRIX:
        shape_short = SHAPE_SHORT[shape]
        path = out_dir / f"phase1_{shape_short}_s{seed}.toml"
        content = TEMPLATE.format(shape=shape, shape_short=shape_short, seed=seed)
        path.write_text(content)
        print(f"wrote {path}")


if __name__ == "__main__":
    main()
