"""Render every sweep TOML from a single (phase, model, shape, seed) matrix.

Originally split across two phases per the agreed design (3 models × 2 shapes × 5 seeds = 30):
  - Phase 1 (4 cells): Qwen2.5-3B × {hyp, exp} × {s0, s1}    [pipeline validation]
  - Phase 2 (26 cells): expand to all 3 models × 5 seeds      [full sweep]

The scope-C cut launches Phase 1 + Phase 2 cross-model cells together at 2 seeds per
(model, shape) — 12 total. Remaining 18 seeds are a "Phase 2 finisher" we'd add later.

Edit SWEEP_MATRIX below and re-run to keep all 12 TOMLs in sync. Per-model parameters
are kept in MODEL_CONFIG.

Usage:
    python scripts/dev/render_sweep_tomls.py
"""
from __future__ import annotations

from pathlib import Path

# (phase, model_key, shape, seed) — keep ordered per phase so file lists are stable
SWEEP_MATRIX = [
    ("phase1", "qwen25_3b", "hyperbolic", 0),
    ("phase1", "qwen25_3b", "hyperbolic", 1),
    ("phase1", "qwen25_3b", "exponential", 0),
    ("phase1", "qwen25_3b", "exponential", 1),
    ("phase2", "qwen3_4b", "hyperbolic", 0),
    ("phase2", "qwen3_4b", "hyperbolic", 1),
    ("phase2", "qwen3_4b", "exponential", 0),
    ("phase2", "qwen3_4b", "exponential", 1),
    ("phase2", "gemma4_e4b", "hyperbolic", 0),
    ("phase2", "gemma4_e4b", "hyperbolic", 1),
    ("phase2", "gemma4_e4b", "exponential", 0),
    ("phase2", "gemma4_e4b", "exponential", 1),
]

# Per-model config: HF id (for [model] name) and hwprop catalog name (for sim_model arg).
# sim_model picks the closest architectural match in hwprop's catalog. Track A's prior
# choice was Qwen2.5-14B across the board (deployment-honest 14B profile for all);
# we instead use per-model architectural latency to match what each policy actually
# experiences during rollout. Both choices are defensible; ours minimizes the gap
# between sim and real wallclock per model, which is what RL trains against.
MODEL_CONFIG = {
    "qwen25_3b": {
        "hf_name": "Qwen/Qwen2.5-3B-Instruct",
        "sim_model": "Qwen2.5-3B",
        "wandb_short": "qwen25-3b",
    },
    "qwen3_4b": {
        "hf_name": "Qwen/Qwen3-4B-Instruct-2507",
        "sim_model": "Qwen3-4B",
        "wandb_short": "qwen3-4b",
    },
    "gemma4_e4b": {
        # gemma-4-E4B-it = Google's Gemma 3n with Matformer-effective 4B params. Closest
        # hwprop catalog entry is Gemma-3-4B (3.x architecture); per-token compute is
        # reasonably similar.
        "hf_name": "google/gemma-4-E4B-it",
        "sim_model": "Gemma-3-4B",
        "wandb_short": "gemma4-e4b",
    },
}

SHAPE_SHORT = {"hyperbolic": "hyp", "exponential": "exp"}

TEMPLATE = """\
# {phase_upper} run: {hf_name}, {shape} reward, seed {seed}.
# 200 steps x batch_size=64 x G=4 = 64 rollouts/step -> ~16 problems/step.
# Estimated wall: ~80-110 min per run on 2x A100-80GB (model-size dependent).
#
# Generated by scripts/dev/render_sweep_tomls.py. Edit the template + matrix there
# to change anything across the sweep.
#
# Watch item: KV pressure. If vLLM OOMs around step 50-100 once the policy uses
# more turns, drop orchestrator.batch_size from 64 -> 32.

max_steps = 200
seq_len = 8192
output_dir = "/cache/runs/{phase}_{model_key}_{shape_short}_s{seed}"

# Top-level [ckpt] triggers RLConfig.auto_setup_ckpt (rl.py:476): creates both
# trainer.ckpt AND orchestrator.ckpt, which validate_shared_ckpt_config requires.
[ckpt]

[wandb]
project = "interoception"
name = "{wandb_short}-{shape_short}-s{seed}"

[model]
name = "{hf_name}"

# --- LoRA wiring. Just [trainer.model.lora] is required; RLConfig.auto_setup_lora
# at rl.py:718 auto-creates orchestrator.model.lora (with name r{{rank}}-a{{alpha}}),
# sets inference.enable_lora=True, and sets inference.max_lora_rank, when this
# block is present.
[trainer.model.lora]
rank = 32
alpha = 32.0
dropout = 0.0
target_modules = ["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"]

[trainer.ckpt.weights]
save_adapter_separately = true

# --- Trainer hyperparameters. prime-rl defaults at this SHA are lr=1e-6 (way
# too low for LoRA RL) and scheduler=constant. The LoRA CI test uses lr=5e-5,
# matched here.
[trainer.optim]
type = "adamw"
lr = 5e-5
max_norm = 1.0
betas1 = 0.9
betas2 = 0.999
weight_decay = 0.01

[trainer.loss]
type = "default"  # discriminated union — required so pydantic picks DefaultLossConfig
kl_tau = 1e-3

[trainer.scheduler]
type = "linear"
warmup_steps = 10  # ramp 0 -> lr over first 10 steps
decay_steps = 10   # decay lr -> 0 over last 10 steps (steps 190-200 of 200)
min_lr = 0.0

[orchestrator]
batch_size = 64
rollouts_per_example = 4   # GRPO group size — all G rollouts share target_s per problem
seed = {seed}

# Override the default filter list to disable enforcement of zero_advantage —
# otherwise the orchestrator evicts the run after MAX_EMPTY_BATCH_ATTEMPTS=3
# consecutive all-zero-advantage batches (hardcoded at orchestrator.py:447-452).
# For sparse-reward low-baseline models (Qwen2.5-3B ~0% correctness), zero-advantage
# batches are common in early training; eviction kills the run before learning starts.
# enforce=false keeps the filter's detection metrics in wandb but lets the rollouts
# pass through to the trainer (zero gradient on those batches, but no eviction).
[[orchestrator.filters]]
type = "gibberish"

[[orchestrator.filters]]
type = "repetition"

[[orchestrator.filters]]
type = "zero_advantage"
enforce = false

[orchestrator.train.sampling]
max_completion_tokens = 256
temperature = 1.0

[[orchestrator.train.env]]
id = "interoception-countdown"
name = "{wandb_short}-{shape_short}-s{seed}-train"
args = {{ problems_jsonl = "/root/data/train.jsonl", target_s_min = 15.0, target_s_max = 120.0, dataset_seed = {seed}, timing_source = "sim", hardware = "A100_80GB", sim_model = "{sim_model}", max_turns = 16, reward_shape = "{shape}", attempt_bonus = 0.05, max_time_multiplier = 5.0 }}

[orchestrator.eval]
interval = 20

[orchestrator.eval.sampling]
max_completion_tokens = 256
temperature = 0.0   # deterministic eval — the deploy-honest setting

# Four eval cells at T=15, 30, 60, 120 — pacing-as-a-function-of-T at the
# extremes of the training distribution. Real timing here. num_examples=100
# cuts binomial CI half-width vs the 30-example baseline.
[[orchestrator.eval.env]]
id = "interoception-countdown"
name = "eval-t15"
num_examples = 100
rollouts_per_example = 1
args = {{ problems_jsonl = "/root/data/eval.jsonl", target_s_min = 15.0, target_s_max = 15.0, max_turns = 16, reward_shape = "{shape}", attempt_bonus = 0.05, max_time_multiplier = 5.0 }}

[[orchestrator.eval.env]]
id = "interoception-countdown"
name = "eval-t30"
num_examples = 100
rollouts_per_example = 1
args = {{ problems_jsonl = "/root/data/eval.jsonl", target_s_min = 30.0, target_s_max = 30.0, max_turns = 16, reward_shape = "{shape}", attempt_bonus = 0.05, max_time_multiplier = 5.0 }}

[[orchestrator.eval.env]]
id = "interoception-countdown"
name = "eval-t60"
num_examples = 100
rollouts_per_example = 1
args = {{ problems_jsonl = "/root/data/eval.jsonl", target_s_min = 60.0, target_s_max = 60.0, max_turns = 16, reward_shape = "{shape}", attempt_bonus = 0.05, max_time_multiplier = 5.0 }}

[[orchestrator.eval.env]]
id = "interoception-countdown"
name = "eval-t120"
num_examples = 100
rollouts_per_example = 1
args = {{ problems_jsonl = "/root/data/eval.jsonl", target_s_min = 120.0, target_s_max = 120.0, max_turns = 16, reward_shape = "{shape}", attempt_bonus = 0.05, max_time_multiplier = 5.0 }}

[inference]
# enable_lora is auto-set to true by auto_setup_lora when [trainer.model.lora] is present.
enable_fp32_lm_head = true
"""


def main() -> None:
    out_dir = Path(__file__).resolve().parents[2] / "configs" / "rl"
    out_dir.mkdir(parents=True, exist_ok=True)
    # Clean prior renders so stale files can't slip in.
    for pattern in ("phase1_*.toml", "phase2_*.toml"):
        for f in out_dir.glob(pattern):
            f.unlink()

    for phase, model_key, shape, seed in SWEEP_MATRIX:
        cfg = MODEL_CONFIG[model_key]
        shape_short = SHAPE_SHORT[shape]
        path = out_dir / f"{phase}_{model_key}_{shape_short}_s{seed}.toml"
        content = TEMPLATE.format(
            phase=phase,
            phase_upper="Phase " + phase.removeprefix("phase"),
            model_key=model_key,
            hf_name=cfg["hf_name"],
            sim_model=cfg["sim_model"],
            wandb_short=cfg["wandb_short"],
            shape=shape,
            shape_short=shape_short,
            seed=seed,
        )
        path.write_text(content)
        print(f"wrote {path.name}")


if __name__ == "__main__":
    main()
